name: mvu_layer
description: An Elm-inspired state management for leveraging benefits from the Elm architecture while still being Dart friendly.
version: 0.1.11
homepage: https://github.com/Nhowka/FlutterMVU

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: