name: mvu_layer
description: An Elm-inspired state management for leveraging benefits from the Elm architecture while still being Dart friendly.
version: 0.3.4
homepage: https://github.com/Nhowka/FlutterMVU

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: